version: "3.9"

services:
    db:
        image: postgres:16
        container_name: pi_db
        restart: unless-stopped
        env_file:
            - ./db.env
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
            interval: 5s
            timeout: 5s
            retries: 10

volumes:
    db_data:
